### ISSUE TITLE
Demo video of the working app

### ISSUE THREAD

**Issue by Leililou** [DIT112-V21/group-17#148]
## Description
Creating a video demonstrating how the app works
### Tasks:

- [x] Make a video of car control

- [x] Include the app demonstration

- [x] Add voice explaning the demo on the video

- [ ] Add explanatory text on the video

- [x] Publish the video on youtube

- [x] Link of the video in the README file

**Comment by Leililou** [comment]
Great Job on the video!! 😀👌

**Comment by Leililou** [comment]
Doooooone!!

**Comment by MaabMohammedali** [comment]
Done
